--------------------------------------------------------
--  File created - Thursday-September-19-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERINFO
--------------------------------------------------------

  CREATE TABLE "PARTCOMP"."USERINFO" 
   (	"ID" VARCHAR2(20 BYTE), 
	"GB_HP" NUMBER, 
	"PERCENTAGE_HP" NUMBER, 
	"PRICE_PER_GB_GP" NUMBER, 
	"GB_MP" NUMBER, 
	"PERCENTAGE_MP" NUMBER, 
	"PRICE_PER_GB_MP" NUMBER, 
	"GB_ROP" NUMBER, 
	"PERCENTAGE_ROP" NUMBER, 
	"PRICE_PER_GB_ROP" NUMBER, 
	"FACTOR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PARTCOMP.USERINFO
SET DEFINE OFF;
Insert into PARTCOMP.USERINFO (ID,GB_HP,PERCENTAGE_HP,PRICE_PER_GB_GP,GB_MP,PERCENTAGE_MP,PRICE_PER_GB_MP,GB_ROP,PERCENTAGE_ROP,PRICE_PER_GB_ROP,FACTOR) values ('0',500,5,72,3500,35,14,6000,60,7,2);
